sonar.projectKey=juergen69_Orderly
sonar.organization=juergen69
sonar.host.url=https://sonarcloud.io
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx
sonar.exclusions=src/**/*.test.ts,src/**/*.test.tsx
sonar.qualitygate.wait=true